#!/command/with-contenv sh

QUEUE_PID=$(pgrep -f "/usr/local/sbin/php /var/www/lsky-pro/artisan queue:work")
if [ -z "$QUEUE_PID" ]; then
    echo "❎ QUEUE STOP."
    exit 1
else
    echo "✅ QUEUE RUN."
    exit 0
fi
